"""empty message

Revision ID: 4da592293ab9
Revises: defbef98d30d
Create Date: 2024-03-18 16:05:08.647200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4da592293ab9'
down_revision = 'defbef98d30d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail', sa.String(), nullable=True))
        batch_op.drop_column('img_large')
        batch_op.drop_column('img_small')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_small', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('img_large', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('thumbnail')

    # ### end Alembic commands ###
