"""empty message

Revision ID: defbef98d30d
Revises: 0be2f912239e
Create Date: 2024-03-18 16:01:37.673559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'defbef98d30d'
down_revision = '0be2f912239e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publisher', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('published', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('published')
        batch_op.drop_column('publisher')

    # ### end Alembic commands ###
